default_platform :ios


platform :ios do

	before_all do
    	setup_circle_ci
  	end
	
    desc 'Build project and executes unit tests'
    lane :unit_test do |option|
		scan(
			include_simulator_logs: false
		)
   end
end
